version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  '@j481240KK'
      POSTGRES_DB:  skillMatchAI
    ports:
      - "5432:5432"   
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  backend:
    build:
      context: . 
    container_name: skillmatch-backend
    ports:
      - "5000:4000"   
    depends_on:
      - postgres   
    environment:
      DATABASE_URL: 'postgres://postgres:%40j481240KK@postgres:5432/skillMatchAI'

volumes:
  postgres-data:  
