name: Deploy to EC2 on Push
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/y
          chmod 600 ~/.ssh/y
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Test SSH Connection
        run:  ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -v -i ~/.ssh/y ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "Connection test"
        
      - name: Deploy to EC2
        env:
          DEBUG: true
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/y ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/project/fullstack-QA-QE/dev/Angular/skillMatchBackend
          docker --version
          docker-compose --version
          git pull origin main 
          docker-compose down
          docker-compose up --build -d
          EOF
